import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable}`}
    >
      <body className="min-h-full flex flex-col font-outfit">
        <Navbar></Navbar>
       {children}
       <Footer></Footer>
       </body>
    </html>
  );
}
